---
title: "Lab Week 8"
author: "Chris Hughes"
date: "3/8/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(tidyverse)
library(sf)
library(tmap)
library(leaflet)
library(spatstat)
library(maptools)


```

```{r, message=FALSE}

oil_spills <- read_csv("oil_spills.csv")

df <- oil_spills %>% 
  filter(`Accident State` == "TX" & `Accident Year` < 2017) %>% 
  group_by(`Accident Year`) %>% 
  summarise(Loss = sum(`Net Loss (Barrels)`))

colnames(df) <- c("Year", "Loss")

ggplot(df, aes(x = Year, y = Loss)) +
  geom_col()

```




### Leaflet Plot of spill locations in texas in 2016


```{r}

df_loc <- oil_spills %>% 
  filter(`Accident State` == "TX" & `Accident Year` == 2016) %>% 
  select(Latitude, Longitude, `Net Loss (Barrels)`)

colnames(df_loc) <- c("Latitude", "Longitude", "Net_Loss")


# convert to geospatial data


oil_sf <- st_as_sf(df_loc, coords = c("Longitude", "Latitude"), crs = 4326)


leaflet(oil_sf) %>% 
  addTiles() %>% 
  addMarkers()


```





## TMap plot with the texas state shapefile



```{r}

states <- st_read(dsn = ".", layer = "states")


tex_border <- states %>% 
  filter(STATE_NAME == "Texas") %>% 
  st_transform(4326)


plot(tex_border)



tm_shape(tex_border) + 
  tm_polygons() +
  tm_shape(oil_sf) +
  tm_dots(size = 0.3)








```


Is random?


## Convert to spatial points patterns

Comb of point data and bounding window






```{r}


spill_sp <- as(oil_sf, "Spatial")



spill_ppp <- as(spill_sp, "ppp")



tx_sp <- as(tex_border, "Spatial")

tx_owin <- as(tx_sp, "owin")


all_ppp <- ppp(spill_ppp$x, spill_ppp$y, window = tx_owin)



```








### Dens ploto

```{r}


plot(density(all_ppp, sigma = 17))

```



Quadrat test for spatial evenness

Are oil spills evenly distributed throughout the state?




```{r,}

oil_qt <- quadrat.test(all_ppp, nx = 5, ny = 5)

oil_qt # data not evenly distributed

plot(all_ppp)
plot(oil_qt, add = TRUE, cex = 0.4)


```




### G Function for nearest neighbor analysis




```{r}

r <- seq(0,1, by = 0.01)

oil_gfun <- envelope(all_ppp, fun = Gest, r = r, nsim = 100)


ggplot(oil_gfun, aes(x = r, y = obs)) +
  geom_line(color = "black") +
  geom_line(aes(x = r, y = theo), color = "firebrick")





```



















